apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lacuna.fullname" . }}-config
  labels:
    {{- include "lacuna.labels" . | nindent 4 }}
data:
  LACUNA_ENVIRONMENT: {{ .Values.config.environment | quote }}
  LACUNA_DEBUG: {{ .Values.config.debug | quote }}
  LACUNA_LOGGING_LEVEL: {{ .Values.config.logLevel | quote }}
  LACUNA_LOGGING_FORMAT: {{ .Values.config.logFormat | quote }}
  LACUNA_POLICY_ENABLED: {{ .Values.config.policy.enabled | quote }}
  LACUNA_CLASSIFICATION_EMBEDDING_ENABLED: {{ .Values.config.classification.embeddingEnabled | quote }}
