apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lacuna.fullname" . }}-secret
  labels:
    {{- include "lacuna.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | default (randAlphaNum 64) | b64enc | quote }}
  database-password: {{ .Values.secrets.databasePassword | default "lacuna" | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | default "" | b64enc | quote }}
